### ISSUE TITLE
UNREG in UDP

### ISSUE THREAD

**Issue by lasitha1991** [ujitha/P2PFileSharer#1]
When we leave the network in UDP mode it gives a exception like this

Response from server:
0012 UNROK 0
java.net.SocketException: Socket closed
    at java.net.PlainDatagramSocketImpl.receive0(Native Method)
    at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:144)
    at java.net.DatagramSocket.receive(DatagramSocket.java:812)
    at communicator.UDPserver.run(UDPserver.java:35)

**Comment by lasitha1991** [comment]
I think it happens only when the routing table is empty

**Comment by pubudu538** [comment]
In the current implementation when we want to leave, we send leave messages to the nodes and close the socket. We don't wait for their respond... I think that's why this exception is thrown. Socket has received a datagram at this point...
